name: release

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'

jobs:

  release:
    runs-on: ubuntu-latest
    outputs:
      semvertag: ${{ steps.getver.outputs.semvertag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Build
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip freeze > requirements.txt
      - name: Build
        run: |
          python -m build
          sphinx-build -b html docsrc/source build/docs
      - name: Read version file
        id: getver
        run: |
          VER=$(cat VERSION)
          echo "VERSION=v$VER" >> $GITHUB_ENV
          echo "semvertag=v$VER" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ env.VERSION }}
          files: |
            dist/*
            requirements.txt

  publish:
    needs:
      - release
    runs-on: ubuntu-latest
    concurrency:
      group: docs
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install cibuildwheel
      - name: Build
        run: |
          python -m build
          sphinx-build -b html docsrc/source build/docs
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/docs
          target-folder: ${{ needs.release.outputs.semvertag }}